language: ruby

sudo: required

services:
    - docker

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -qq install php5-cli

install:
    - ./kingdom.sh start test
    - sleep 80
    - ./kingdom.sh log

script:
    - ./kingdom.sh test
