language: ruby

sudo: required

services:
    - docker
    
before_install:
  - pip install codecov

install:
    - ./kingdom.sh start test
    - sleep 60
    - ./kingdom.sh log

script:
    - ./kingdom.sh test

after_success:
  - codecov
