language: php
php:
  - 5.6
#install:
#   - composer install

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update
  - composer install

script:
  - vendor/codeception/codeception/codecept run
