language: php
php:
  - 5.4
  - 5.5
  - 5.6
#install:
#   - composer install

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update
  - composer install

script:
  - php codecept run