language: php
#php:
#  - 5.5
#install:
#   - composer install

sudo: required

services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
    - ./kingdom.sh start

#install:
#  - composer self-update
#  - composer install

script:
  # Symfony
  - php codecept build -c frameworks-yii-basic/tests
  - php codecept build -c frameworks-phalcon
  - php codecept build -c frameworks-laravel
  - php codecept build -c frameworks-symfony
  - '[[ "$TRAVIS_PHP_VERSION" == "5.4" ]] || php codecept build -c frameworks-l5'
  - php codecept build -c frameworks-zf1
  - php codecept build -c frameworks-zf2
  - vendor/codeception/codeception/codecept run
