language: ruby

sudo: required

services:
    - docker

env:
    - PHP_VERSION=5.4
    - PHP_VERSION=5.5
    - PHP_VERSION=5.6
    - PHP_VERSION=7.0

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -qq install php5-cli

install:
    - ./kingdom.sh start

script:
  # Symfony
  - ./vendor/codeception/codeception/codecept build -c frameworks-symfony
  - ./vendor/codeception/codeception/codecept run
