language: ruby

sudo: required

services:
    - docker

env:
    - PHP_VERSION=5.4
    - PHP_VERSION=5.5
    - PHP_VERSION=5.6
    - PHP_VERSION=7.0

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -qq install php5-cli

install:
    - ./kingdom.sh start

script:
  # Symfony
  - php codecept build -c frameworks-yii-basic/tests
  - php codecept build -c frameworks-phalcon
  - php codecept build -c frameworks-laravel
  - php codecept build -c frameworks-symfony
  - '[[ "$TRAVIS_PHP_VERSION" == "5.4" ]] || php codecept build -c frameworks-l5'
  - php codecept build -c frameworks-zf1
  - php codecept build -c frameworks-zf2
  - vendor/codeception/codeception/codecept run
