fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rottenwood_user:
    resource: "@RottenwoodUserBundle/Controller/"
    type:     annotation
    prefix:   /

rottenwood_kingdom:
    resource: "@RottenwoodKingdomBundle/Controller/"
    type:     annotation
    prefix:   /


