services:
    kingdom.user_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\UserRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\User"]

    kingdom.room_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\RoomRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\Room"]

    kingdom.room_type_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\RoomTypeRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\RoomType"]

    kingdom.item_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\ItemRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\Infrastructure\Item"]

    kingdom.inventory_item_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\InventoryItemRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\InventoryItem"]

    kingdom.money_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\MoneyRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\Money"]

    kingdom.user_service:
        class: Rottenwood\KingdomBundle\Service\UserService
        arguments:
            - @snc_redis.default
            - @kingdom.user_repository
            - @kingdom.inventory_item_repository

    # Логгер
    kingdom.logger:
        class: Monolog\Logger
        arguments: ['default']
        calls:
          - ['pushHandler', [@kingdom.logger_handler.commands]]

    kingdom.logger_handler.commands:
        class: Monolog\Handler\StreamHandler
        arguments: [ "%kernel.logs_dir%/game_logs/commands.log"]
        calls:
          - ['setFormatter', [@kingdom.logger_formatter]]

    kingdom.logger_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%message%%\n"
