services:
    kingdom.user_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\UserRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\User"]

    kingdom.room_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\RoomRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\Room"]

    kingdom.room_type_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\RoomTypeRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\RoomType"]

    kingdom.item_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\ItemRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\Infrastructure\Item"]

    kingdom.inventory_item_repository:
        class: Rottenwood\KingdomBundle\Entity\Infrastructure\InventoryItemRepository
        factory_service: "doctrine.orm.entity_manager"
        factory_method: getRepository
        arguments: ["Rottenwood\KingdomBundle\Entity\Infrastructure\InventoryItem"]

    kingdom.user_service:
        class: Rottenwood\KingdomBundle\Service\UserService
        arguments: [@snc_redis.default, @kingdom.user_repository]
