services:
    # Слушатель событий FOSUserBundle
    fosuser.listener:
        class: "Rottenwood\UserBundle\EventListener\FOSUserListener"
        arguments: [@router, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_subscriber }
