services:
    # Слушатель событий FOSUserBundle
    fosuser.listener:
        class: "Rottenwood\UserBundle\EventListener\FOSUserListener"
        arguments: [@router, @kingdom.room_repository]
        tags:
            - { name: kernel.event_subscriber }
