services:
    # Слушатель событий FOSUserBundle
    fosuser.listener:
        class: "Rottenwood\UserBundle\EventListener\FOSUserListener"
        arguments:
            - @router
            - @kernel
            - @kingdom.room_repository
            - @kingdom.money_repository
        tags:
            - { name: kernel.event_subscriber }
